[project]
name = "ecs-abm-benchmark"
version = "0.1.0"
description = "ECS vs Mesa ABM benchmarking project"
authors = [
    {name = "mlrx-potindji",email = "malraux.potindji@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "mesa (>=3.5.0,<4.0.0)",
    "esper (>=3.7,<4.0)",
    "matplotlib (>=3.10.8,<4.0.0)"
]

[tool.poetry]
packages = [
    { include = "ecs", from = "src" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
