[project]
name = "epidemic-sim-benchmark"
version = "0.1.0"
description = "Epidemic simulation benchmark for ECS and Mesa agent-based models"
authors = [
    {name = "mlrx-potindji",email = "malraux.potindji@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "mesa (>=3.5.0,<4.0.0)",
    "esper (>=3.7,<4.0)",
    "numpy (>=2.0.0,<3.0.0)",
    "scipy (>=1.14.0,<2.0.0)",
    "pandas (>=2.0.0,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "ema-workbench (>=2.5.3,<3.0.0)"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epidemic_sim"]
